const users = {
  ram: "69d10cfcfb3d788d98a6237c",
  rahim: "69d10ef526cd7ddf3fd2fbe8",
  sonali: "69d10f0c26cd7ddf3fd2fbef",
};

const listings = [
  {
    title: "Luxury Beach Villa",
    description: "Ocean-facing villa with private pool",
    image: {
      url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
      filename: "beach1.jpg",
    },
    price: 4000,
    location: "Goa",
    country: "India",
    region: "southeast asia",
    categories: ["beach", "luxury"],
    owner: users.ram,
    geometry: { type: "Point", coordinates: [73.8567, 15.2993] },
  },
  {
    title: "Mountain Cabin Retreat",
    description: "Peaceful cabin with scenic mountain views",
    image: {
      url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470",
      filename: "mountain1.jpg",
    },
    price: 1800,
    location: "Manali",
    country: "India",
    region: "southeast asia",
    categories: ["mountain", "camping"],
    owner: users.rahim,
    geometry: { type: "Point", coordinates: [77.1887, 32.2432] },
  },
  {
    title: "Modern City Loft",
    description: "Stylish apartment in the heart of the city",
    image: {
      url: "https://images.unsplash.com/photo-1493809842364-78817add7ffb",
      filename: "city1.jpg",
    },
    price: 3200,
    location: "Mumbai",
    country: "India",
    region: "southeast asia",
    categories: ["city", "iconic cities"],
    owner: users.sonali,
    geometry: { type: "Point", coordinates: [72.8777, 19.076] },
  },
  {
    title: "Desert Camp Experience",
    description: "Stay under the stars in a desert camp",
    image: {
      url: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee",
      filename: "desert1.jpg",
    },
    price: 1500,
    location: "Jaisalmer",
    country: "India",
    region: "middle east",
    categories: ["camping"],
    owner: users.ram,
    geometry: { type: "Point", coordinates: [70.9167, 26.9157] },
  },
  {
    title: "Lake View Cottage",
    description: "Relaxing cottage with lake view",
    image: {
      url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb",
      filename: "lake1.jpg",
    },
    price: 2200,
    location: "Nainital",
    country: "India",
    region: "southeast asia",
    categories: ["trending"],
    owner: users.rahim,
    geometry: { type: "Point", coordinates: [79.4636, 29.3919] },
  },
  {
    title: "Forest Treehouse",
    description: "Unique stay among lush green forest",
    image: {
      url: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e",
      filename: "forest1.jpg",
    },
    price: 2700,
    location: "Kerala",
    country: "India",
    region: "southeast asia",
    categories: ["camping", "trending"],
    owner: users.sonali,
    geometry: { type: "Point", coordinates: [76.2711, 10.8505] },
  },
  {
    title: "Snowy Mountain Chalet",
    description: "Perfect winter escape with snow views",
    image: {
      url: "https://images.unsplash.com/photo-1519681393784-d120267933ba",
      filename: "snow1.jpg",
    },
    price: 3500,
    location: "Shimla",
    country: "India",
    region: "southeast asia",
    categories: ["mountain"],
    owner: users.ram,
    geometry: { type: "Point", coordinates: [77.1734, 31.1048] },
  },
  {
    title: "Island Beach Hut",
    description: "Private island hut with crystal clear water",
    image: {
      url: "https://images.unsplash.com/photo-1470770841072-f978cf4d019e",
      filename: "island1.jpg",
    },
    price: 5000,
    location: "Andaman",
    country: "India",
    region: "southeast asia",
    categories: ["beach"],
    owner: users.rahim,
    geometry: { type: "Point", coordinates: [92.7265, 11.7401] },
  },
  {
    title: "Royal Heritage Haveli",
    description: "Experience royal living in a traditional haveli",
    image: {
      url: "https://images.unsplash.com/photo-1467269204594-9661b134dd2b",
      filename: "haveli1.jpg",
    },
    price: 2800,
    location: "Jaipur",
    country: "India",
    region: "middle east",
    categories: ["iconic cities"],
    owner: users.sonali,
    geometry: { type: "Point", coordinates: [75.7873, 26.9124] },
  },
  {
    title: "Riverside Camping Site",
    description: "Camping by the river with bonfire",
    image: {
      url: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429",
      filename: "river1.jpg",
    },
    price: 1600,
    location: "Rishikesh",
    country: "India",
    region: "southeast asia",
    categories: ["camping"],
    owner: users.ram,
    geometry: { type: "Point", coordinates: [78.2676, 30.0869] },
  },
];

module.exports = listings;
